name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: adopt@1.11
      - name: version
        run: node --version
      - name: Checking your code format
        run: sbt scalafmtCheckAll
      - name: Run tests
        env:
          NODE_OPTIONS: --max_old_space_size=4096
        run: |
          sbt facade/test demo/fastLinkJS
